const autoCaptcha = document.getElementById("AutoGeneratedValue")
const userCaptcha = document.getElementById("userCaptchaValue")
const message = document.getElementById("message")

// 页面加载时生成验证码
window.onload = generateCaptcha

let CAPTCHAText = ''

function generateCaptcha() {
    // 生成包含数字和小写字母的随机字符串
    let random = Math.random().toString(36).substring(2, 8)
    
    // 将随机字符串转换为字符数组
    let chars = random.split('')
    
    // 随机选择 1-3 个位置，将其字符转换为大写
    const uppercaseCount = Math.floor(Math.random() * 3) + 1

    for (let i = 0; i < uppercaseCount; i++) {
        const position = Math.floor(Math.random() * chars.length)
        // 只对字母进行大写转换
        if (/[a-z]/.test(chars[position])) {
            chars[position] = chars[position].toUpperCase()
        }
    }
    // 将字符数组重新组合为字符串
    random = chars.join('')
    autoCaptcha.innerHTML = random
    CAPTCHAText = random
    message.innerHTML = ''
    userCaptcha.value = ''
}

function checkCaptcha() {
    if (userCaptcha.value === CAPTCHAText) {
        message.innerHTML = '验证成功'
        message.style.color = 'green'
    } else {
        message.innerHTML = '验证失败'
        message.style.color = 'red'
    }
}